version: '3.3'

networks:
  front:
#      driver: "overlay"

volumes:
  mongodata:
    external: true
    # driver: "nfs"

services: 
  mongo:
    image: mongo
    container_name: mongo
    command: --nojournal
    networks:
      - front
    volumes:
     - mongodata:/data/db

  orion:
    image: fiware/orion
    container_name: orion
    ports:
      - "1026:1026"
    networks:
      - front
    command: -dbhost mongo

  server:
    container_name: express-api
    build:
      context: ./server
    env_file: ./server/.env
    ports:
      - "3001:3001"
    networks:
      - front
    command: "npm run dev"

  client:
    container_name: nuxt-client
    build:
      context: ./client
    ports:
      - "3000:3000"
    networks:
      - front
    volumes:
      - ./client:/app/client:rw
    command: "npm run dev"
