version: '3.3'

services:
    mongo:
      image: mongo:latest
      container_name: mongo
      # ports:
      #   - 27017:27017
      volumes:
        - mongodb_data_container:/data/db
      networks: 
        - test-network

    orion:
      image: fiware/orion
      links:
        - mongo
      ports:
        - "1026:1026"
      command: -dbhost mongo

    server:
      container_name: express-api
      build:
        context: ./server
      env_file: ./server/.env
      networks: 
        - test-network
      ports:
        - "3001:3001"
      command: "npm run dev"

    client:
      container_name: nuxt-client
      build:
        context: ./client
      ports:
        - "3000:3000"
      command: "npm run dev"

volumes:
  mongodb_data_container:

networks: 
  test-network: